name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  go_router: ^7.0.0
  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0
  path_provider: ^2.0.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.8

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  isar_generator: ^3.0.0
 # isar_inspector: any
  build_runner: ^2.0.0
  

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

